require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
    NewCops: enable

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
